[directory]
truncation_length=0
truncate_to_repo=true

[package]
disabled=true
[erlang]
disabled=true
[golang]
disabled=true
[helm]
disabled=true
[java]
disabled=true
[julia]
disabled=true
[kotlin]
disabled=true
[nim]
disabled=true
[nodejs]
disabled=true
[ocaml]
disabled=true
[perl]
disabled=true
[php]
disabled=true
[purescript]
disabled=true
[python]
disabled=true
[ruby]
disabled=true
[rust]
disabled=true
[swift]
disabled=true
